{{- if .Values.networkPolicy.enabled }}
apiVersion: "networking.k8s.io/v1"
kind: "NetworkPolicy"
metadata:
  name: {{ include "fluent-bit.fullname" . | quote }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}