apiVersion: v1
data:
  master.conf: |-
    dir /data
    # User-supplied master configuration:
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    # End of master configuration
  redis.conf: |-
    # User-supplied common configuration:
    # see https://redis.io/docs/manual/eviction/
    maxmemory 768mb
    maxmemory-policy allkeys-lru
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly yes
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
     # End of common configuration
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.envName }}-insights-api-redis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: insights-api-redis
    stage: {{ .Values.envName }}
  name: {{ .Values.envName }}-insights-api-redis-configuration
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  ping_liveness_local.sh: >-
    #!/bin/bash


    [[ -f $REDIS_PASSWORD_FILE ]] && export REDIS_PASSWORD="$(<
    "${REDIS_PASSWORD_FILE}")"

    [[ -n "$REDIS_PASSWORD" ]] && export REDISCLI_AUTH="$REDIS_PASSWORD"

    response=$(
      timeout -s 3 $1 \
      redis-cli \
        -h localhost \
        -p $REDIS_PORT \
        ping
    )

    if [ "$?" -eq "124" ]; then
      echo "Timed out"
      exit 1
    fi